/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/__root";
import { Route as Char43pageRouteImport } from "./../routes/+page";
import { Route as DashboardRouteImport } from "./../routes/dashboard";
import { Route as DashboardIndexRouteImport } from "./../routes/dashboard.index";
import { Route as DashboardPostsRouteImport } from "./../routes/dashboard.posts";
import { Route as DashboardPostsPostIdRouteImport } from "./../routes/dashboard.posts.$postId";
import { Route as DashboardPostsIndexRouteImport } from "./../routes/dashboard.posts.index";

const Char43pageRoute = Char43pageRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/index",
  path: "/index",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: "/posts",
  path: "/posts",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardPostsPostIdRoute = DashboardPostsPostIdRouteImport.update({
  id: "/$postId",
  path: "/$postId",
  getParentRoute: () => DashboardPostsRoute,
} as any);
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: "/index",
  path: "/index",
  getParentRoute: () => DashboardPostsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof Char43pageRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/dashboard/index": typeof DashboardIndexRoute;
  "/dashboard/posts": typeof DashboardPostsRouteWithChildren;
  "/dashboard/posts/$postId": typeof DashboardPostsPostIdRoute;
  "/dashboard/posts/index": typeof DashboardPostsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof Char43pageRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/dashboard/index": typeof DashboardIndexRoute;
  "/dashboard/posts": typeof DashboardPostsRouteWithChildren;
  "/dashboard/posts/$postId": typeof DashboardPostsPostIdRoute;
  "/dashboard/posts/index": typeof DashboardPostsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof Char43pageRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/dashboard/index": typeof DashboardIndexRoute;
  "/dashboard/posts": typeof DashboardPostsRouteWithChildren;
  "/dashboard/posts/$postId": typeof DashboardPostsPostIdRoute;
  "/dashboard/posts/index": typeof DashboardPostsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/dashboard/index"
    | "/dashboard/posts"
    | "/dashboard/posts/$postId"
    | "/dashboard/posts/index";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/dashboard/index"
    | "/dashboard/posts"
    | "/dashboard/posts/$postId"
    | "/dashboard/posts/index";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/dashboard/index"
    | "/dashboard/posts"
    | "/dashboard/posts/$postId"
    | "/dashboard/posts/index";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  Char43pageRoute: typeof Char43pageRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof Char43pageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/index": {
      id: "/dashboard/index";
      path: "/index";
      fullPath: "/dashboard/index";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/posts": {
      id: "/dashboard/posts";
      path: "/posts";
      fullPath: "/dashboard/posts";
      preLoaderRoute: typeof DashboardPostsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/posts/$postId": {
      id: "/dashboard/posts/$postId";
      path: "/$postId";
      fullPath: "/dashboard/posts/$postId";
      preLoaderRoute: typeof DashboardPostsPostIdRouteImport;
      parentRoute: typeof DashboardPostsRoute;
    };
    "/dashboard/posts/index": {
      id: "/dashboard/posts/index";
      path: "/index";
      fullPath: "/dashboard/posts/index";
      preLoaderRoute: typeof DashboardPostsIndexRouteImport;
      parentRoute: typeof DashboardPostsRoute;
    };
  }
}

interface DashboardPostsRouteChildren {
  DashboardPostsPostIdRoute: typeof DashboardPostsPostIdRoute;
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute;
}

const DashboardPostsRouteChildren: DashboardPostsRouteChildren = {
  DashboardPostsPostIdRoute: DashboardPostsPostIdRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
};

const DashboardPostsRouteWithChildren = DashboardPostsRoute._addFileChildren(
  DashboardPostsRouteChildren,
);

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardPostsRoute: typeof DashboardPostsRouteWithChildren;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsRoute: DashboardPostsRouteWithChildren,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  Char43pageRoute: Char43pageRoute,
  DashboardRoute: DashboardRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
