/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PlayersRouteImport } from "./routes/players";
import { Route as FreeAgencyRouteImport } from "./routes/free-agency";
import { Route as CapTrackerRouteImport } from "./routes/cap-tracker";
import { Route as IndexRouteImport } from "./routes/index";

const PlayersRoute = PlayersRouteImport.update({
  id: "/players",
  path: "/players",
  getParentRoute: () => rootRouteImport,
} as any);
const FreeAgencyRoute = FreeAgencyRouteImport.update({
  id: "/free-agency",
  path: "/free-agency",
  getParentRoute: () => rootRouteImport,
} as any);
const CapTrackerRoute = CapTrackerRouteImport.update({
  id: "/cap-tracker",
  path: "/cap-tracker",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/cap-tracker": typeof CapTrackerRoute;
  "/free-agency": typeof FreeAgencyRoute;
  "/players": typeof PlayersRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/cap-tracker": typeof CapTrackerRoute;
  "/free-agency": typeof FreeAgencyRoute;
  "/players": typeof PlayersRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/cap-tracker": typeof CapTrackerRoute;
  "/free-agency": typeof FreeAgencyRoute;
  "/players": typeof PlayersRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/cap-tracker" | "/free-agency" | "/players";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/cap-tracker" | "/free-agency" | "/players";
  id: "__root__" | "/" | "/cap-tracker" | "/free-agency" | "/players";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CapTrackerRoute: typeof CapTrackerRoute;
  FreeAgencyRoute: typeof FreeAgencyRoute;
  PlayersRoute: typeof PlayersRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/players": {
      id: "/players";
      path: "/players";
      fullPath: "/players";
      preLoaderRoute: typeof PlayersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/free-agency": {
      id: "/free-agency";
      path: "/free-agency";
      fullPath: "/free-agency";
      preLoaderRoute: typeof FreeAgencyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cap-tracker": {
      id: "/cap-tracker";
      path: "/cap-tracker";
      fullPath: "/cap-tracker";
      preLoaderRoute: typeof CapTrackerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapTrackerRoute: CapTrackerRoute,
  FreeAgencyRoute: FreeAgencyRoute,
  PlayersRoute: PlayersRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
