/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PlayersImport } from './routes/players'
import { Route as FreeAgencyImport } from './routes/free-agency'
import { Route as CapTrackerImport } from './routes/cap-tracker'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PlayersRoute = PlayersImport.update({
  path: '/players',
  getParentRoute: () => rootRoute,
} as any)

const FreeAgencyRoute = FreeAgencyImport.update({
  path: '/free-agency',
  getParentRoute: () => rootRoute,
} as any)

const CapTrackerRoute = CapTrackerImport.update({
  path: '/cap-tracker',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cap-tracker': {
      id: '/cap-tracker'
      path: '/cap-tracker'
      fullPath: '/cap-tracker'
      preLoaderRoute: typeof CapTrackerImport
      parentRoute: typeof rootRoute
    }
    '/free-agency': {
      id: '/free-agency'
      path: '/free-agency'
      fullPath: '/free-agency'
      preLoaderRoute: typeof FreeAgencyImport
      parentRoute: typeof rootRoute
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CapTrackerRoute,
  FreeAgencyRoute,
  PlayersRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cap-tracker",
        "/free-agency",
        "/players"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cap-tracker": {
      "filePath": "cap-tracker.tsx"
    },
    "/free-agency": {
      "filePath": "free-agency.tsx"
    },
    "/players": {
      "filePath": "players.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
