# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish
        run: dotnet publish --configuration Release --property OutputPath=${{ env.DOTNET_ROOT }}/mfl/

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: mfl
          path: ${{ env.DOTNET_ROOT }}/mfl/publish

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: mfl

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_447CCD33623F44DBAB3AEF0552926F05 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_104E1030154D42129619DD3C2F8BF6E4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0C8A43A3D309461BBD85E2BD2A11E888 }}

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "mfl-freeagency"
          slot-name: "production"
          package: .
